---
- name: Add PPA for libopencv-nonfree for SURF and SIFT features
  apt_repository: repo='ppa:xqms/opencv-nonfree'
- name: Install opencv dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - ipython
    - python-dev
    - python-numpy
    - libgtk2.0-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - python-numpy
    - python-scipy
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev
    - libopencv-contrib-dev
    - libopencv-core-dev
    - libopencv-dev
    - libopencv-features2d-dev
    - libopencv-nonfree-dev
    - libopencv-gpu-dev
    - python-opencv
